export { Chat } from './Chat'
export { Gallery } from './Gallery'
export { Diary } from './Diary'
export { Todos } from './Todos'
export { PdfView } from './PdfView'
export { PptView } from './PptView'
